---
title: "Gallup Relative Status Health Outcome Regression Analysis"
author: "Daniel O'Leary"
date: "1/11/2021"
output:
  github_document:
    toc: true
    toc_depth: 5
---

```{r, include = FALSE}
if (!require("pacman")) install.packages("pacman")

pacman::p_load(
  tidyverse, 
  haven,
  lme4,
  lm.beta,
  sjPlot,
  stargazer
)
```

```{r, include = FALSE}
sinfo <- data.frame(Sys.info())
machine <- sinfo$Sys.info..[4]

machine_path <- 
  ifelse(
    machine %in% c("sussman-rp-mbpro.local", "sussman-rp-mbpro.lan"), 
    "/Users/djolear/Google Drive/", 
    "G:/My Drive/"
  )

source(paste0(machine_path, "research/projects/gallup/gallup_analysis_1/relative_status_analysis/regression_results_munge.R"))

dfg_rs <-
  read_rds("D:/data/gallup/exports/dfg_rs.rds")

dfg_rs <-
  dfg_rs %>% 
  mutate_at(
    vars(
      sex, 
      employment_all,
      race,
      married
    ),
    as.factor
  )
```

```{r}
contrasts(dfg_rs$sex) <- contr.sum(2)
contrasts(dfg_rs$employment_all) <- contr.sum(2)
contrasts(dfg_rs$race) <- contr.sum(5)
contrasts(dfg_rs$married) <- contr.sum(6)
```

```{r}
# c <- contr.treatment(2)
# c
# my.coding <- matrix(rep(1/2, 2), ncol = 1)
# my.simple = c - my.coding
# my.simple
# 
# contrasts(dfg_rs$sex) <- my.simple
# contrasts(dfg_rs$employment_all) <- my.simple
# 
# 
# c <- contr.treatment(5)
# my.coding <- matrix(rep(1/5, 20), ncol = 4)
# my.simple = c - my.coding
# my.simple
# 
# contrasts(dfg_rs$race) <- my.simple
# 
# 
# c <- contr.treatment(6)
# my.coding <- matrix(rep(1/6, 30), ncol = 5)
# my.simple = c - my.coding
# my.simple
# 
# contrasts(dfg_rs$married) <- my.simple
```


# Analysis


## Health outcomes

### BMI

```{r}
lm_bmi_geo <-
  lm(
    bmi_scale ~
      raw_income_scale +
      median_income_county_scale +
      physicians_scale +
      unweighted_pop_county_scale +
      median_monthly_housing_cost_county_scale +
      land_area_2010_scale +
      education_scale +
      employment_all +
      sex +
      age_scale +
      race +
      married + 
      year,
    data = dfg_rs 
  )

summary(lm_bmi_geo)

lm_bmi_demo <-
  lm(
    bmi_scale ~
      raw_income_scale +
      median_income_demo_scale +
      physicians_scale +
      unweighted_pop_county_scale +
      median_monthly_housing_cost_county_scale +
      land_area_2010_scale +
      education_scale +
      employment_all +
      sex +
      age_scale +
      race +
      married + 
      year,
    data = dfg_rs 
  )

summary(lm_bmi_demo)
```


### Diabetes

```{r}
lm_diab_geo <-
  glm(
    diabetes ~
      raw_income_scale +
      median_income_county_scale +
      physicians_scale +
      unweighted_pop_county_scale +
      median_monthly_housing_cost_county_scale +
      land_area_2010_scale +
      education_scale +
      employment_all +
      sex +
      age_scale +
      race +
      married + 
      year,
    family = "binomial",
    data = dfg_rs %>% mutate(diabetes = ifelse(diabetes == 1, 1, ifelse(diabetes == 2, 0, NA)))
  )

summary(lm_diab_geo)

lm_diab_demo <-
  glm(
    diabetes ~
      raw_income_scale +
      median_income_demo_scale +
      physicians_scale +
      unweighted_pop_county_scale +
      median_monthly_housing_cost_county_scale +
      land_area_2010_scale +
      education_scale +
      employment_all +
      sex +
      age_scale +
      race +
      married + 
      year,
    family = "binomial",
    data = dfg_rs %>% mutate(diabetes = ifelse(diabetes == 1, 1, ifelse(diabetes == 2, 0, NA)))
  )

summary(lm_diab_demo)
```


### High blood pressure

```{r}
lm_hbp_geo <-
  glm(
    hbp ~
      raw_income_scale +
      median_income_county_scale +
      physicians_scale +
      unweighted_pop_county_scale +
      median_monthly_housing_cost_county_scale +
      land_area_2010_scale +
      education_scale +
      employment_all +
      sex +
      age_scale +
      race +
      married + 
      year,
    family = "binomial",
    data = dfg_rs %>% mutate(hbp = ifelse(hbp == 1, 1, ifelse(hbp == 2, 0, NA)))
  )

summary(lm_hbp_geo)

lm_hbp_demo <-
  glm(
    hbp ~
      raw_income_scale +
      median_income_demo_scale +
      physicians_scale +
      unweighted_pop_county_scale +
      median_monthly_housing_cost_county_scale +
      land_area_2010_scale +
      education_scale +
      employment_all +
      sex +
      age_scale +
      race +
      married + 
      year,
    family = "binomial",
    data = dfg_rs %>% mutate(hbp = ifelse(hbp == 1, 1, ifelse(hbp == 2, 0, NA)))
  )

summary(lm_hbp_demo)
```


### Depression

```{r}
lm_dep_geo <-
  glm(
    depression ~
      raw_income_scale +
      median_income_county_scale +
      physicians_scale +
      unweighted_pop_county_scale +
      median_monthly_housing_cost_county_scale +
      land_area_2010_scale +
      education_scale +
      employment_all +
      sex +
      age_scale +
      race +
      married + 
      year,
    family = "binomial",
    data = dfg_rs %>% mutate(depression = ifelse(depression == 1, 1, ifelse(depression == 2, 0, NA)))
  )

summary(lm_dep_geo)

lm_dep_demo <-
  glm(
    depression ~
      raw_income_scale +
      median_income_demo_scale +
      physicians_scale +
      unweighted_pop_county_scale +
      median_monthly_housing_cost_county_scale +
      land_area_2010_scale +
      education_scale +
      employment_all +
      sex +
      age_scale +
      race +
      married + 
      year,
    family = "binomial",
    data = dfg_rs %>% mutate(depression = ifelse(depression == 1, 1, ifelse(depression == 2, 0, NA)))
  )

summary(lm_dep_demo)
```



### Obesity

```{r}
lm_obe_geo <-
  glm(
    obese ~
      raw_income_scale +
      median_income_county_scale +
      physicians_scale +
      unweighted_pop_county_scale +
      median_monthly_housing_cost_county_scale +
      land_area_2010_scale +
      education_scale +
      employment_all +
      sex +
      age_scale +
      race +
      married + 
      year,
    family = "binomial",
    data = dfg_rs %>% mutate(obese = ifelse(obese == 1, 0, ifelse(obese == 0, 1, NA)))
  )

summary(lm_obe_geo)

lm_obe_demo <-
  glm(
    smoke ~
      raw_income_scale +
      median_income_demo_scale +
      physicians_scale +
      unweighted_pop_county_scale +
      median_monthly_housing_cost_county_scale +
      land_area_2010_scale +
      education_scale +
      employment_all +
      sex +
      age_scale +
      race +
      married + 
      year,
    family = "binomial",
    data = dfg_rs %>% mutate(obese = ifelse(obese == 1, 0, ifelse(obese == 0, 1, NA))) 
  )

summary(lm_obe_demo)
```


### Self-reported health

```{r}
lm_srh_geo <-
  lm(
    scale(sr_health) ~
      raw_income_scale +
      median_income_county_scale +
      physicians_scale +
      unweighted_pop_county_scale +
      median_monthly_housing_cost_county_scale +
      land_area_2010_scale +
      education_scale +
      employment_all +
      sex +
      age_scale +
      race +
      married + 
      year,
    data = dfg_rs %>% mutate(sr_health = ifelse(sr_health %in% c(1:5), 6 - sr_health, NA))
  )

summary(lm_srh_geo)

lm_srh_demo <-
  lm(
    scale(sr_health) ~
      raw_income_scale +
      median_income_demo_scale +
      physicians_scale +
      unweighted_pop_county_scale +
      median_monthly_housing_cost_county_scale +
      land_area_2010_scale +
      education_scale +
      employment_all +
      sex +
      age_scale +
      race +
      married + 
      year,
    data = dfg_rs %>% mutate(sr_health = ifelse(sr_health %in% c(1:5), 6 - sr_health, NA))
  )

summary(lm_srh_demo)
```


### Height

```{r}
lm_ht_geo <-
  lm(
    scale(HEIGHT) ~
      raw_income_scale +
      median_income_county_scale +
      physicians_scale +
      unweighted_pop_county_scale +
      median_monthly_housing_cost_county_scale +
      land_area_2010_scale +
      education_scale +
      employment_all +
      sex +
      age_scale +
      race +
      married + 
      year,
    data = dfg_rs 
  )

summary(lm_ht_geo)

lm_ht_demo <-
  lm(
    scale(HEIGHT) ~
      raw_income_scale +
      median_income_demo_scale +
      physicians_scale +
      unweighted_pop_county_scale +
      median_monthly_housing_cost_county_scale +
      land_area_2010_scale +
      education_scale +
      employment_all +
      sex +
      age_scale +
      race +
      married + 
      year,
    data = dfg_rs 
  )

summary(lm_ht_demo)
```


## Regression tables

### Demographic reference

```{r}
stargazer(
  lm_diab_demo, lm_hbp_demo, lm_obe_demo, lm_bmi_demo, lm_dep_demo, lm_srh_demo,
  ci = TRUE,
  type = "html", digits = 2,
  out = "regression_table_health_outcomes_demo.doc",
  dep.var.labels = c("diabetes", "high blood pressure", "obesity", "BMI", "depression", "self-reported health"),
  covariate.labels =
    c(
      "own income",
      "demographic reference \n median income",
      "ratio of physicians",
      "population",
      "housing cost",
      "land area",
      "education",
      "employment = employed",
      "sex = male",
      "age",
      "race = white",
      "race = African American",
      "race = Asian",
      "race = American Indian \n Alaska native",
      "marital status = single",
      "marital status = married",
      "marital status = separated",
      "marital status = divorced",
      "marital status = widowed"
    ),
  omit = c("year"),
  star.char = c("*", "**", "***"),
  star.cutoffs = c(0.05, 0.01, 0.001),
  notes = c("* p<0.05; ** p<0.01; *** p<0.001")
)
```


### Geographic reference

```{r}
stargazer(
  lm_diab_geo, lm_hbp_geo, lm_obe_geo, lm_bmi_geo, lm_dep_geo, lm_srh_geo,
  ci = TRUE,
  type = "html", digits = 2,
  out = "regression_table_health_outcomes_geo.doc",
  dep.var.labels = c("diabetes", "high blood pressure", "obesity", "BMI", "depression", "self-reported health"),
  covariate.labels =
    c(
      "own income",
      "geographic reference \n median income",
      "ratio of physicians",
      "population",
      "housing cost",
      "land area",
      "education",
      "employment = employed",
      "sex = male",
      "age",
      "race = white",
      "race = African American",
      "race = Asian",
      "race = American Indian \n Alaska native",
      "marital status = single",
      "marital status = married",
      "marital status = separated",
      "marital status = divorced",
      "marital status = widowed"
    ),
  omit = c("year"),
  star.char = c("*", "**", "***"),
  star.cutoffs = c(0.05, 0.01, 0.001),
  notes = c("* p<0.05; ** p<0.01; *** p<0.001")
)
```

